# Generated by Django 2.2.3 on 2019-07-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=250)),
                ('status', models.CharField(choices=[('WA', 'Waiting'), ('WR', 'Working'), ('DN', 'Done')], default='WA', max_length=2)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
