# Generated by Django 2.2.3 on 2019-07-21 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WA', 'Waiting'), ('WR', 'Working'), ('DN', 'Done')], default='Waiting', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=250)),
                ('choice', models.CharField(blank=True, default='Waiting', max_length=10)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.Status')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
