# Generated by Django 2.2.3 on 2019-07-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
