# Generated by Django 2.2.3 on 2019-07-21 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='action',
        ),
        migrations.AlterField(
            model_name='todo',
            name='choice',
            field=models.ForeignKey(default='Waiting', on_delete=django.db.models.deletion.CASCADE, to='todos.Status'),
        ),
    ]
