# Generated by Django 2.2.3 on 2019-07-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20190721_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
        migrations.AddField(
            model_name='todo',
            name='choice',
            field=models.CharField(blank=True, default='Waiting', max_length=10),
        ),
    ]
